version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: dangvien_nginx
    ports:
      - "81:80"
      - "443:443"
    # Remove the read-only flag to avoid issues with modifying files in /etc/nginx/conf.d and /etc/nginx/ssl.
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - dangvien_network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tho493/dang-vien:latest
    container_name: dangvien_web
    expose:
      - "80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=dangvien_db
    networks:
      - dangvien_network
    restart: unless-stopped

  db:
    image: mariadb:10.4
    container_name: dangvien_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dangvien_db
      MYSQL_USER: dangvien_user
      MYSQL_PASSWORD: dangvien_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - dangvien_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dangvien_phpmyadmin
    ports:
      - "9081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - dangvien_network
    restart: unless-stopped

networks:
  dangvien_network:
    driver: bridge

volumes:
  db_data:

